# Base configs
baseurl: "https://michaelperez023.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Mosaicos Rosalba Pérez"
subtitle: "See the world through my eyes!"
author: "Michael Pérez"
header:
 title: "Mosaicos"
 subtitle: "por Rosalba Pérez"
footer:
 name: "Mosaicos hecho por Rosalba Pérez"
 bio: "Yo hago mosaicos"
 github: "github"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"

theme: jekyll-theme-cayman
